packages:
  all:
    require:
    - any_of: ['%intel-oneapi-compilers@=2025.3.0']
      when: '%intel-oneapi-compilers'
    - any_of: ['%gcc@=12.4.0']
      when: '%gcc'
  mpi:
    buildable: false
    require:
    - intel-oneapi-mpi@2021.17
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2025.3.0
      prefix: /pw/apps/intel/2025.3.0
      modules:
      - tbb/2022.3
      - compiler-rt/2025.3.0
      - umf/1.0.2
      - compiler/2025.3.0
      extra_attributes:
        compilers:
          c: /pw/apps/intel/2025.3.0/compiler/2025.3/bin/icx
          cxx: /pw/apps/intel/2025.3.0/compiler/2025.3/bin/icpx
          fortran: /pw/apps/intel/2025.3.0/compiler/2025.3/bin/ifx
        environment:
          set:
            MODULES_AUTO_HANDLING: '1'
          prepend_path:
            MODULEPATH: /pw/apps/modules/intel/2025.3.0
  intel-oneapi-mpi:
    buildable: false
    externals:
    - spec: intel-oneapi-mpi@2021.17
      prefix: /pw/apps/intel/2025.3.0
      modules:
      - mpi/2021.17
  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2025.3
      prefix: /pw/apps/intel/2025.3.0
      modules:
      - mkl/2025.3
  intel-oneapi-tbb:
    buildable: false
    externals:
    - spec: intel-oneapi-tbb@2022.3
      prefix: /pw/apps/intel/2025.3.0
      modules:
      - tbb/2022.3
  gcc:
    buildable: false
    externals:
    - spec: gcc@12.4.0 languages:='c,c++,fortran'
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj
      modules:
      - gcc/12.4.0
      extra_attributes:
        compilers:
          c: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/bin/gcc
          cxx: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/bin/g++
          fortran: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/bin/gfortran

