# This template minimizes skylab-dev to just the required parts of the jedi-mpas-env virtual env
# needed for compiling subsets of jedi with the compilers provided in the Nvidia HPC SDK.
#
# So, this template is basically a listing of the packages within jedi-mpas-env, but with some
# packages excluded for reasons such as:
# - python is excluded because we don't dare compile it with nvhpc, and it's just too cumbersome
#   to list all of python's dependencies and all relevant python packages as being compiled with
#   the fallback gcc compiler.
#   NB: Python is needed so should be installed from the distro's package manager!
# - gsibec is excluded because it doesn't build with nvhpc, but as it is Fortran code we don't
#   have the option of falling back to gcc.
# - various file-format libraries are excluded because they're not needed yet, and excluding
#   them for now is simply a better use of resources.
# - jasper is excluded because it's difficult to compile
#
spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  specs:

  # packages from base-env
  # removed python
  # removed py-* packages
  - hdf5
  - nccmp
  - netcdf-c
  - netcdf-fortran
  - parallel-netcdf
  - parallelio
  - wget

  # packages from jedi-base-env
  # removed gsibec
  # removed py-* packages
  # removed ncview
  # and these file-format libraries not needed to run jedi from IODA files
  # removed bufr, bufr-query, netcdf-cxx4
  # removed odc
  # removed eccodes
  # removed hdf
  - bison
  - boost
  - ecbuild
  - eckit
  - ecmwf-atlas
  - eigen
  - fckit
  - fftw
  - flex
  - git-lfs
  - gsl-lite
  - jedi-cmake
  - nlohmann-json
  - nlohmann-json-schema-validator
  - udunits

  # packages from jedi-mpas-env
  # removed jasper
  - metis

  # added packages
  - netcdf-cxx4
  - zlib
