name: Nightly 02 Get Spack-Stack Develop

runs:
  using: "composite"
  steps:
  - name: Nightly 02 Get Spack-Stack Develop
    shell: bash
    run: |
      RUNID=`date +"%Y%m%d"`
      cd util/weekly_build
      ./2_GetSpackStackDevelop.sh ${RUNID} ${BASEDIR} ${PLATFORM}
