packages:
  all:
    compiler:: [intel@2021.10.0]
    providers:
      mpi:: [intel-oneapi-mpi@2021.10.0]
      # Remove the next three lines to switch to intel-oneapi-mkl
      blas:: [openblas]
      fftw-api:: [fftw]
      lapack:: [openblas]
    # spack concretizer gets confused and wants an AVX512 architecture for some packages
    require:
      - 'arch=linux-rocky8-skylake'

### MPI, Python, MKL
  mpi:
    buildable: False
  intel-oneapi-mpi:
    externals:
    - spec: intel-oneapi-mpi@2021.10.0%intel@2021.10.0 +classic-names
      prefix: /opt/intel/oneapi/2023.2
      modules:
      - intel/2023.2
  intel-oneapi-mkl:
    # Remove buildable: False and uncomment externals section below to use intel-oneapi-mkl
    buildable: False
    #externals:
    #- spec: intel-oneapi-mkl@2023.2.0%intel@2021.10.0
    #  prefix: /opt/intel/oneapi/2023.2
    #  modules:
    #  - intel/2023.2
  # Remove this section to switch to intel-oneapi-mkl
  ectrans:
    require::
    - '@1.2.0 ~mkl +fftw'
  gsibec:
    require::
    - '@1.2.1 ~mkl'
  py-numpy:
    require::
    - '@1.26'
    - '^openblas'
  # *DH
  zlib-ng:
    require:
      - '~shared'

