packages:
  all:
    require:
    - any_of: ['%llvm@=22.1.0']
      when: '%llvm'
  mpi:
    buildable: false
    require: [openmpi@=5.0.10]
  openmpi:
    buildable: false
    externals:
    - spec: openmpi@=5.0.10
      prefix: /ford1/share/gmao_SIteam/MPI/openmpi/5.0.10/llvm-flang-22.1.0
