packages:
  mpi:
    buildable: False
    require:
    - "intel-oneapi-mpi@2021.15"
  intel-oneapi-compilers:
    externals:
    - spec: intel-oneapi-compilers@2025.1.1
      prefix: /contrib/oneapi/2025.1.1
      modules:
      - umf/0.10.0
      - tbb/2022.1
      - compiler-rt/2025.1.1
      - compiler/2025.1.1
      extra_attributes:
        compilers:
          c: /contrib/oneapi/2025.1.1/compiler/2025.1/bin/icx
          cxx: /contrib/oneapi/2025.1.1/compiler/2025.1/bin/icpx
          fortran: /contrib/oneapi/2025.1.1/compiler/2025.1/bin/ifx

  intel-oneapi-mpi:
    buildable: false
    externals:
    - spec: intel-oneapi-mpi@2021.15
      prefix: /contrib/oneapi/2025.1.1
      modules:
      - mpi/2021.15
  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2025.1
      prefix: /contrib/oneapi/2025.1.1
      modules:
      - mkl/2025.1
  intel-oneapi-tbb:
    buildable: false
    externals:
    - spec: intel-oneapi-tbb@2022.2
      prefix: /contrib/oneapi/2025.1.1
      modules:
      - tbb/2022.1
  intel-oneapi-runtime:
    # LINK TO BUG REPORT HERE
    #buildable: false
    externals:
    - spec: intel-oneapi-runtime@2025.1.1
      prefix: /contrib/oneapi/2025.1.1
      modules:
      - umf/0.10.0
      - tbb/2022.1
      - compiler-rt/2025.1.1
      - compiler/2025.1.1
  gcc:
    externals:
    - spec: gcc@11.5.0 languages:='c,c++'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
  gcc-runtime:
    externals:
    - spec: gcc-runtime@11.5.0
      prefix: /usr
