config:
  build_jobs: 6

  # Overrides for spack build and staging areas to speed up builds
  # and avoid errors with Lustre file locking and xattr issues
  build_stage:  /discover/nobackup/projects/gmao/SIteam/spack-stack/cache/build_stage
  test_stage:   /discover/nobackup/projects/gmao/SIteam/spack-stack/cache/test_stage
  source_cache: /discover/nobackup/projects/gmao/SIteam/spack-stack/cache/source_cache
  misc_cache:   /discover/nobackup/projects/gmao/SIteam/spack-stack/cache/misc_cache
