packages:
  all:
    target: [x86_64_v3]
  awscli-v2:
    require:
    - "@2.22.4"
  cairo:
    variants: +pic
  ewok-env:
    require:
    - +ecflow
  fontconfig:
    variants: +pic
  met:
    variants: +python +grib2 +graphics +lidar2nc +modis
  parallelio:
    require:
    - +pnetcdf
  pixman:
    variants: +pic
  py-awscrt:
    require:
    - "@0.19.19"
  py-botocore:
    require:
    - "@1.34.162"
  py-boto3:
    require:
    - "@1.34.162"
  py-netcdf4:
    require:
    - "@1.7.2"

  # System packages installed during the container build.
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@9.4
      prefix: /usr
  diffutils:
    buildable: false
    externals:
    - spec: diffutils@3.10
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.9.0
      prefix: /usr
  git:
    buildable: false
    externals:
    - spec: git@2.43.0~tcltk
      prefix: /usr
  git-lfs:
    buildable: false
    externals:
    - spec: git-lfs@3.4.1
      prefix: /usr
  grep:
    externals:
    - spec: grep@3.11
      prefix: /usr
  llvm:
    buildable: false
    externals:
    - spec: llvm@14.0.6
      prefix: /usr
  perl:
    buildable: false
    externals:
    - spec: perl@5.38.2
      prefix: /usr
