compilers:
- compiler:
    spec: intel@2021.5.0
    paths:
      cc: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/icc
      cxx: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/icpc
      f77: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
      fc: /apps/oneapi/compiler/2022.0.2/linux/bin/intel64/ifort
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules:
    - intel/2022.1.2
    environment:
      prepend_path:
        PATH: '/apps/gnu/gcc-9.2.0/bin'
        LD_LIBRARY_PATH: '/apps/gnu/gcc-9.2.0/lib64'
        CPATH: '/apps/gnu/gcc-9.2.0/include'
    extra_rpaths: []
- compiler:
    spec: gcc@13.3.0
    paths:
      cc: /contrib/spack-stack/installs/gnu/13.3.0/bin/gcc
      cxx: /contrib/spack-stack/installs/gnu/13.3.0/bin/g++
      f77: /contrib/spack-stack/installs/gnu/13.3.0/bin/gfortran
      fc: /contrib/spack-stack/installs/gnu/13.3.0/bin/gfortran
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules:
    - gnu/13.3.0
    environment:
      prepend_path:
        MODULEPATH: '/contrib/spack-stack/installs/gnu/modulefiles'
        PATH: '/contrib/spack-stack/installs/ucx/ucx-1.20.0/bin'
        LD_LIBRARY_PATH: '/contrib/spack-stack/installs/ucx/ucx-1.20.0/lib'
        PKG_CONFIG_PATH: '/contrib/spack-stack/installs/ucx/ucx-1.20.0/lib/pkgconfig'
    extra_rpaths: []
- compiler:
    spec: oneapi@2024.2.1
    paths:
      cc: /apps/oneapi/compiler/2024.2/bin/icx
      cxx: /apps/oneapi/compiler/2024.2/bin/icpx
      f77: /apps/oneapi/compiler/2024.2/bin/ifort
      fc: /apps/oneapi/compiler/2024.2/bin/ifort
    flags: {}
    operating_system: rocky8
    target: x86_64
    modules:
    - intel/2024.2.1
    environment:
      prepend_path:
        PATH: '/apps/gnu/gcc-13.2.0/bin'
        LD_LIBRARY_PATH: '/apps/gnu/gcc-13.2.0/lib64'
        CPATH: '/apps/gnu/gcc-13.2.0/include'
    extra_rpaths: []
