packages:
  all:
    compiler:: [gcc@13.3.0]
    providers:
      mpi:: [openmpi@4.1.6]
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.1.6~cuda~cxx~cxx_exceptions~java+lustre~memchecker+pmi~static~wrapper-rpath schedulers=slurm fabrics=ucx
      prefix: /contrib/spack-stack/installs/openmpi/4.1.6
      modules:
      - gnu/13.3.0
      - openmpi/4.1.6
