compilers:
- compiler:
    spec: oneapi@2024.2.1
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags: {}
    operating_system: sles15
    target: x86_64
    modules:
    - PrgEnv-intel/8.6.0
    - intel/2024.2
    - craype/2.7.34
    - cray-libsci/24.11.0
    - libfabric/1.20.1
    environment:
      prepend_path:
        LD_LIBRARY_PATH: '/opt/cray/libfabric/1.20.1/lib64:/opt/cray/pe/libsci/24.07.0/INTEL/2023.2/x86_64/lib:/usr/lib64/gcc/x86_64-suse-linux/12:/opt/intel/oneapi/compiler/2024.2/lib'
      set:
        # OpenSUSE on Gaea C6 sets CONFIG_SITE so
        # Automake-based builds are installed in lib64
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths:
      - /opt/intel/oneapi/compiler/2024.2/lib
- compiler:
    spec: intel@2023.2.0
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    flags:
      cflags: "-gcc-name=/usr/bin/gcc-12"
      cxxflags: "-gxx-name=/usr/bin/g++-12 -gcc-name=/usr/bin/gcc-12 -static-libstdc++"
      fflags: "-gcc-name=/usr/bin/gcc-12"
    operating_system: sles15
    target: x86_64
    modules:
    - PrgEnv-intel/8.5.0
    - intel-classic/2023.2.0
    - craype/2.7.30
    - libfabric/1.20.1
    environment:
      prepend_path:
        LD_LIBRARY_PATH: '/opt/cray/libfabric/1.20.1/lib64:/opt/cray/pe/libsci/24.07.0/INTEL/2023.2/x86_64/lib:/usr/lib64/gcc/x86_64-suse-linux/12'
      set:
        # OpenSUSE on Gaea C6 sets CONFIG_SITE so
        # Automake-based builds are installed in lib64
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
- compiler:
    spec: gcc@12.3.0
    paths:
      cc: /usr/bin/gcc-12
      cxx: /usr/bin/g++-12
      f77: /usr/bin/gfortran-12
      fc:  /usr/bin/gfortran-12
    flags: {}
    operating_system: sles15
    target: x86_64
    modules:
    - PrgEnv-gnu/8.6.0
    - gcc-native/12.3
    - craype/2.7.34
    - libfabric/1.20.1
    - cray-libsci/24.11.0
    - libfabric/1.20.1
    environment: 
      prepend_path:
        LD_LIBRARY_PATH: '/opt/cray/libfabric/1.20.1/lib64:/opt/cray/pe/libsci/24.07.0/INTEL/2023.2/x86_64/lib:/usr/lib64/gcc/x86_64-suse-linux/12:/opt/intel/oneapi/compiler/2024.2/lib'
    extra_rpaths:
      - /opt/intel/oneapi/compiler/2024.2/lib
