packages:
  all:
    require:
    - any_of: ['gcc@=13.3.1']
      when: '%gcc'
  mpi:
    buildable: False
    require:
    - cray-mpich@8.1.32
  cray-mpich:
    buildable: False
    externals:
    - spec: cray-mpich@8.1.32
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/gnu/12.3
      modules:
      - libfabric/1.22.0
      - craype-network-ofi
      - cray-mpich/8.1.32
  gcc:
    buildable: False
    externals:
    - spec: gcc@13.3.1 languages:='c,c++,fortran'
      prefix: /opt/cray/pe/gcc-native/13/bin
      modules:
        - PrgEnv-gnu/8.6.0
        - gcc-native/13.2
      extra_attributes:
        compilers:
          c: /usr/bin/gcc-13
          cxx: /usr/bin/g++-13
          fortran: /usr/bin/gfortran-13
        environment:
          set:
            CONFIG_SITE: ''
            PE_GCC_EXTERNAL: native
          prepend_path:
            LD_LIBRARY_PATH: '/opt/cray/libfabric/1.22.0/lib64:/opt/cray/pe/libsci/25.09.0/GNU/13.2/x86_64/lib:/usr/lib64/gcc/x86_64-suse-linux/12'
