# NOTE: Module configuration changes should be appropriately reflected
#         in both modules_lmod.yaml and modules_tcl.yaml.
modules:
  default:
    roots:
      tcl: $env/modules
    tcl:
      projections:
        # Note: These translations of compiler and MPI library names must match the ALIASES
        # dictionary in spack-ext/lib/jcsda-emc/spack-stack/stack/meta_modules.py
        # Defaults
        '^intel-oneapi-compilers-classic^intel-oneapi-mpi': 'impi/{^mpi.version}/intel/{compiler.version}/{name}/{version}'
        '^intel-oneapi-compilers-classic^mpi': '{^mpi.name}/{^mpi.version}/intel/{compiler.version}/{name}/{version}'
        '^intel-oneapi-compilers-classic': 'intel/{compiler.version}/{name}/{version}'
        '^intel-oneapi-compilers^intel-oneapi-mpi': 'impi/{^mpi.version}/oneapi/{compiler.version}/{name}/{version}'
        '^intel-oneapi-compilers^mpi': '{^mpi.name}/{^mpi.version}/oneapi/{compiler.version}/{name}/{version}'
        '^intel-oneapi-compilers': 'oneapi/{compiler.version}/{name}/{version}'
        ^intel-oneapi-mpi: 'impi/{^mpi.version}/{compiler.name}/{compiler.version}/{name}/{version}'
        ^mpi: '{^mpi.name}/{^mpi.version}/{compiler.name}/{compiler.version}/{name}/{version}'
        all: '{compiler.name}/{compiler.version}/{name}/{version}'
        # The special cases - Intel classic compilers
        'nlohmann-json ^intel-oneapi-compilers-classic': 'intel/{compiler.version}/json/{version}'
        'nlohmann-json-schema-validator ^intel-oneapi-compilers-classic': 'intel/{compiler.version}/json-schema-validator/{version}'
        'libjpeg-turbo ^intel-oneapi-compilers-classic': 'intel/{compiler.version}/libjpeg/{version}'
        'prod-util ^intel-oneapi-compilers-classic': 'intel/{compiler.version}/prod_util/{version}'
        # The special cases - Intel LLVM compilers
        'nlohmann-json ^intel-oneapi-compilers': 'oneapi/{compiler.version}/json/{version}'
        'nlohmann-json-schema-validator ^intel-oneapi-compilers': 'oneapi/{compiler.version}/json-schema-validator/{version}'
        'libjpeg-turbo ^intel-oneapi-compilers': 'oneapi/{compiler.version}/libjpeg/{version}'
        'prod-util ^intel-oneapi-compilers': 'oneapi/{compiler.version}/prod_util/{version}'
        # The special cases - other compilers
        nlohmann-json: '{compiler.name}/{compiler.version}/json/{version}'
        nlohmann-json-schema-validator: '{compiler.name}/{compiler.version}/json-schema-validator/{version}'
        libjpeg-turbo: '{compiler.name}/{compiler.version}/libjpeg/{version}'
        prod-util: '{compiler.name}/{compiler.version}/prod_util/{version}'
      exclude:
      # List of packages for which we don't need modules
      - apple-libunwind
      - apple-libuuid
      - autoconf
      - automake
      - berkeley-db
      - bison
      - bzip2
      - compiler-wrapper
      - diffutils
      - expat
      - findutils
      - fixesproto
      - flex
      - freetype
      - gcc-runtime
      - gdbm
      - gmake
      - googletest
      - hwloc
      - inputproto
      - intel-oneapi-runtime
      - kbproto
      - libaec
      - libbsd
      - libedit
      - libevent
      - libfabric
      - libffi
      - libgeotiff
      - libice
      - libiconv
      - libm
      - libpciaccess
      - libpthread-stubs
      - libsigsegv
      - libsm
      - libtiff
      - libtool
      - libx11
      - libxau
      - libxcb
      - libxdmcp
      - libxext
      - libxfixes
      - libxi
      - libxml
      - libxml2
      - libxrandr
      - libxrender
      - libxxf86vm
      - lz4
      - m4
      - mysql
      - nasm
      - ncurses
      - openssh
      - openssl
      - perl
      - pkgconf
      - pkg-config
      - py-cython
      - py-poetry-core
      - qt
      - randrproto
      - readline
      - renderproto
      - xcb-proto
      - xextproto
      - xf86vidmodeproto
      - xproto
      - xrandr
      - xtrans
      - xz
      - yaksa
      # By default, do not create compiler modules
      - apple-clang
      - gcc
      - intel-oneapi-compilers
      - intel-oneapi-compilers-classic
      - llvm
      # By default, do not create MPI modules
      - cray-mpich
      - intel-mpi
      - intel-oneapi-mpi
      - mpich
      - mpt
      - openmpi
      hash_length: 0
      all:
        autoload: direct
        environment:
          set:
            '{name}_ROOT': '{prefix}'
        suffixes:
          +debug: 'debug'
          build_type=Debug:  'debug'
      ecmwf-atlas:
        environment:
          set:
            'atlas_ROOT': '{prefix}'
      esmf:
        environment:
          set:
            'ESMFMKFILE': '{prefix}/lib/esmf.mk'
        suffixes:
          ~openmp: 'noopenmp'
      ip:
        suffixes:
          ~openmp: 'noopenmp'
      neptune-env:
        suffixes:
          ~openmp: 'noopenmp'
      libpng:
        environment:
          set:
            'PNG_ROOT': '{prefix}'
      madis:
        environment:
          set:
            'MADIS_ROOT': '{prefix}'
      mapl:
        suffixes:
          ^esmf@8.6.1~debug ~openmp snapshot=none: 'esmf-8.6.1-noopenmp'
          ^esmf@8.6.1+debug ~openmp snapshot=none: 'esmf-8.6.1-debug-noopenmp'
          ^esmf@8.6.1~debug +openmp snapshot=none: 'esmf-8.6.1'
          ^esmf@8.6.1+debug +openmp snapshot=none: 'esmf-8.6.1-debug'
          ^esmf@8.8.0~debug ~openmp snapshot=none: 'esmf-8.8.0-noopenmp'
          ^esmf@8.8.0+debug ~openmp snapshot=none: 'esmf-8.8.0-debug-noopenmp'
          ^esmf@8.8.0~debug +openmp snapshot=none: 'esmf-8.8.0'
          ^esmf@8.8.0+debug +openmp snapshot=none: 'esmf-8.8.0-debug'
          ^esmf@8.9.1~debug ~openmp snapshot=none: 'esmf-8.9.1-noopenmp'
          ^esmf@8.9.1+debug ~openmp snapshot=none: 'esmf-8.9.1-debug-noopenmp'
          ^esmf@8.9.1~debug +openmp snapshot=none: 'esmf-8.9.1'
          ^esmf@8.9.1+debug +openmp snapshot=none: 'esmf-8.9.1-debug'
      fms:
        suffixes:
          constants=GFS: 'gfs-constants'
          constants=GEOS: 'geos-constants'
      openmpi:
        environment:
          set:
            'OMPI_MCA_rmaps_base_oversubscribe': '1'
            'PRTE_MCA_rmaps_default_mapping_policy': ':oversubscribe'
      bacio:
        environment:
          set:
            'BACIO_INC4': '{prefix}/include_4'
            'BACIO_INC8': '{prefix}/include_8'
            'BACIO_LIB4': '{prefix}/lib/libbacio_4.a'
            'BACIO_LIB8': '{prefix}/lib/libbacio_8.a'
      bufr:
        environment:
          set:
            'BUFR_ROOT': '{prefix}'
      crtm:
        environment:
          set:
            'CRTM_INC': '{prefix}/include'
            'CRTM_LIB': '{prefix}/lib/libcrtm.a'
      g2tmpl:
        environment:
          set:
            'G2TMPL_INC': '{prefix}/include'
            'G2TMPL_LIB': '{prefix}/lib/libg2tmpl.a'
      gfsio:
        environment:
          set:
            'GFSIO_INC': '{prefix}/include'
            'GFSIO_LIB': '{prefix}/lib/libgfsio.a'
            'GFSIO_INC4': '{prefix}/include'
            'GFSIO_LIB4': '{prefix}/lib/libgfsio.a'
      grib-util:
        environment:
          set:
            'CNVGRIB': '{prefix}/bin/cnvgrib'
            'COPYGB': '{prefix}/bin/copygb'
            'COPYGB2': '{prefix}/bin/copygb2'
            'DEGRIB2': '{prefix}/bin/degrib2'
            'GRB2INDEX': '{prefix}/bin/grb2index'
            'GRBINDEX': '{prefix}/bin/grbindex'
            'GRIB2GRIB': '{prefix}/bin/grib2grib2'
            'TOCGRIB': '{prefix}/bin/tocgrib'
            'TOCGRIB2': '{prefix}/bin/tocgrib2'
            'TOCGRIB2SUPER': '{prefix}/bin/tocgrib2super'
            'WGRIB': '{prefix}/bin/wgrib'
      landsfcutil:
        environment:
          set:
            'LANDSFCUTIL_INC4': '{prefix}/include_4'
            'LANDSFCUTIL_INCd': '{prefix}/include_d'
            'LANDSFCUTIL_LIB4': '{prefix}/lib/liblandsfcutil_4.a'
            'LANDSFCUTIL_LIBd': '{prefix}/lib/liblandsfcutil_d.a'
      nemsio:
        environment:
          set:
            'NEMSIO_INC': '{prefix}/include'
            'NEMSIO_LIB': '{prefix}/lib64/libnemsio.a'
            'MKGFSNEMSIOCTL': '{prefix}/mkgfsnemsioctl'
            'NEMSIO_CHGDATE': '{prefix}/bin/nemsio_chgdate'
            'NEMSIO_GET': '{prefix}/bin/nemsio_get'
            'NEMSIO_READ': '{prefix}/bin/nemsio_read'
      nemsiogfs:
        environment:
          set:
            'NEMSIOGFS_INC': '{prefix}/include'
            'NEMSIOGFS_LIB': '{prefix}/lib'
      prod-util:
        environment:
          set:
            'MDATE': '{prefix}/bin/mdate'
            'NDATE': '{prefix}/bin/ndate'
            'NHOUR': '{prefix}/bin/nhour'
            'FSYNC': '{prefix}/bin/fsync_file'
      sigio:
        environment:
          set:
            'SIGIO_INC': '{prefix}/include'
            'SIGIO_LIB': '{prefix}/lib/libsigio.a'
            'SIGIO_INC4': '{prefix}/include'
            'SIGIO_LIB4': '{prefix}/lib/libsigio.a'
      sfcio:
        environment:
          set:
            'SFCIO_INC': '{prefix}/include'
            'SFCIO_LIB': '{prefix}/lib/libsfcio.a'
      w3nco:
        environment:
          set:
            'W3NCO_INC4': '{prefix}/include_4'
            'W3NCO_INC8': '{prefix}/include_8'
            'W3NCO_INCd': '{prefix}/include_d'
            'W3NCO_LIB4': '{prefix}/lib/libw3nco_4.a'
            'W3NCO_LIB8': '{prefix}/lib/libw3nco_8.a'
            'W3NCO_LIBd': '{prefix}/lib/libw3nco_d.a'
      wgrib2:
        environment:
          set:
            'WGRIB2_INC': '{prefix}/include'
            'WGRIB2_LIB': '{prefix}/lib64/libwgrib2.so'
            'WGRIB2': '{prefix}/bin/wgrib2'
      wrf-io:
        environment:
          set:
            'WRF_IO_INC': '{prefix}/include'
            'WRF_IO_LIB': '{prefix}/lib/libwrf_io.a'
      upp:
        environment:
          set:
            'UPP_INC': '{prefix}/include'
            'UPP_LIB': '{prefix}/lib/libupp.a'
