packages:
    # Compiler preferences
    c:
      prefer:
      - llvm
    cxx:
      prefer:
      - llvm
    fortran:
      prefer:
      - llvm
    # Virtual provider settings
    blas:
      require:
      - openblas
    fftw-api:
      require:
      - fftw
    lapack:
      require:
      - openblas
    # Individual package settings
    ectrans:
      require:
      - +fftw
