packages:
    all:
      prefer:
      - '%clang'
    # Virtual provider settings
    blas:
      require: [openblas]
    fftw-api:
      require: [fftw]
    lapack:
      require: [openblas]
    # Individual package settings
    ectrans:
      require:
      - +fftw
