packages:
    # Compiler preferences
    c:
      prefer:
      - intel-oneapi-compilers
    cxx:
      prefer:
      - intel-oneapi-compilers
    fortran:
      prefer:
      - intel-oneapi-compilers
    # Virtual package settings
    blas:
      require: ['intel-oneapi-mkl']
    fftw-api:
      require: ['intel-oneapi-mkl']
    lapack:
      require: ['intel-oneapi-mkl']
    # Individual package settings
    antlr:
      require:
      - '%gcc'
    bison:
      require:
      - '%gcc'
    cmake:
      require:
      - '%gcc'
    ectrans:
      require:
      - +mkl ~fftw
    gmake:
      require:
      - '%gcc'
    libbsd:
      require:
      - '%gcc'
    libmd:
      require:
      - '%gcc'
    met:
      require:
      - +shared-intel
    nco:
      require:
      - '%gcc'
    parallel-netcdf:
      require:
      - +shared-intel
    py-maturin:
      require:
      - '%gcc'
    py-scipy:
      require:
      - 'cxxflags="-O1"'
    qt:
      require:
      - '%gcc'
