packages:
    c:
      prefer:
      - clang
    cxx:
      prefer:
      - clang
    fortran:
      prefer:
      - clang
    all:
      providers:
        blas: [openblas]
        fftw-api: [fftw]
        lapack: [openblas]
    ectrans:
      require:
      - ~mkl +fftw
    ip:
      require:
      - '^openblas'
      - '~openmp'
    py-numpy:
      require:
      - '^openblas'
