packages:
    # Compiler preferences
    c:
      prefer:
      - intel-oneapi-compilers
    cxx:
      prefer:
      - intel-oneapi-compilers
    fortran:
      prefer:
      - intel-oneapi-compilers
    # Virtual package settings
    blas:
      require:
      - intel-oneapi-mkl
    fftw-api:
      require:
      - intel-oneapi-mkl
    lapack:
      require:
      - intel-oneapi-mkl
    # Individual package settings
    antlr:
      require:
      - '%c,cxx=gcc'
    bison:
      require:
      - '%c,cxx=gcc'
    cmake:
      require:
      - '%c,cxx=gcc'
    ectrans:
      require:
      - +mkl
      - ~fftw
    elfutils:
      require:
      - '@0.191:'
    libelf:
      buildable: false
    gmake:
      require:
      - '%c=gcc'
    go:
      require:
      - '%c,cxx=gcc'
    libbsd:
      require:
      - '%c=gcc'
    libmd:
      require:
      - '%c=gcc'
    met:
      require:
      - +shared-intel
    nco:
      require:
      - '%c,cxx=gcc'
    oops:
      require:
      - +mkl
    parallel-netcdf:
      require:
      - +shared-intel
    py-maturin:
      require:
      - '%c=gcc'
    py-scipy:
      require:
      - 'cxxflags="-O1"'
    qt:
      require:
      - '%c,cxx=gcc'
    rust:
      require:
      - '%c,cxx=gcc'
