packages:
    all:
      prefer:
      - '%oneapi'
      providers:
        blas: [intel-oneapi-mkl]
        fftw-api: [intel-oneapi-mkl]
        lapack: [intel-oneapi-mkl]
    antlr:
      require:
      - '%gcc'
    bison:
      require:
      - '%gcc'
    cmake:
      require:
      - '%gcc'
    ectrans:
      require:
      - +mkl ~fftw
    gmake:
      require:
      - '%gcc'
    ip:
      require:
      - '^intel-oneapi-mkl'
    libbsd:
      require:
      - '%gcc'
    libmd:
      require:
      - '%gcc'
    met:
      require:
      - +shared-intel
    nco:
      require:
      - '%gcc'
    parallel-netcdf:
      require:
      - +shared-intel
    py-maturin:
      require:
      - '%gcc'
    py-numpy:
      require:
      - '^intel-oneapi-mkl'
    qt:
      require:
      - '%gcc'
    # Prevent issues with fault Intel libraries
    # when using tar etc by building zlib-api with gcc
    zlib:
      require:
      - '%gcc'
    zlib-ng:
      buildable: False
