packages:
    all:
      prefer:
      - "%[when=%c]c=gcc %[when=%cxx]cxx=gcc %[when=%fortran]fortran=gcc"
    # Virtual provider settings
    blas:
      require: [openblas]
    fftw-api:
      require: [fftw]
    lapack:
      require: [openblas]
    # Individual package settings
    ectrans:
      require:
      - +fftw
