packages:
  all:
    compiler:: [gcc@12.2.0]
    providers:
      mpi:: [openmpi@4.1.4]
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.1.4%gcc@11.3.1~cuda~cxx~cxx_exceptions~java~memchecker+pmi+static~wrapper-rpath
      prefix: /apps/spack-managed/gcc-12.2.0/openmpi-4.1.4-hf3dkf6r56x3klzcgs3u7esgt3fhnk63
      modules:
      - gcc/12.2.0
      - openmpi/4.1.4
  py-numpy:
    require::
    - '@1.26'
    - '^openblas'
