packages:
  all:
    compiler:: [gcc@13.3.0]
    providers:
      mpi:: [openmpi@4.1.6]
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.1.6~atomics~cuda~cxx~cxx_exceptions~java+legacylaunchers~lustre~memchecker~openshmem~orterunprefix+pmi+romio+rsh~singularity+static+vt+wrapper-rpath fabrics=ucx schedulers=slurm
      prefix: /apps/contrib/spack-stack/openmpi/installs/openmpi/4.1.6
      modules:
      - gnu/13.3.0
      - openmpi/4.1.6

  ectrans:
    require::
    - '~mkl +fftw'
  gsibec:
    require::
    - '~mkl'
  py-numpy:
    require::
    - '@1.26'
    - '^openblas'
