name: Nightly 01 Directory Setup
#description: Display a GitHub Actions log files - requires CI_DIR environment variable from caller

runs:
  using: "composite"
  steps:
  - name: Nightly 01 Directory Setup
    shell: bash
    run: |
      RUNID=`date +"%Y%m%d"`
      # DH* TODO REMOVE LATER?
      RUNDIR=${BASEDIR}/${RUNID}
      rm -vfr ${RUNDIR}
      # *DH
      cd util/weekly_build
      ./1_DirectorySetup.sh ${RUNID} ${BASEDIR} ${PLATFORM}
