# Template for NEPTUNE operations
#
spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  specs:
  - neptune-env ~debug +openmp +espc ~ncview ^esmf@=9.0.0b10

  packages:
    # Turn off python variant for esmf
    esmf:
      require:
      - ~python
