packages:
  all:
    compiler:: [gcc@10.2.0]
    providers:
      mpi:: [openmpi@4.1.1]
  mpi:
    buildable: False
  openmpi:
    externals:
    - spec: openmpi@4.1.1%gcc@10.2.0
      modules:
      - Master
      - prgenv-gnu-openmpi/10.2.0-4.1.1
  gcc-runtime:
    externals:
    - spec: gcc-runtime@10.2.0%gcc@10.2.0
      prefix: /p/app/compilers/gcc/10.2.0
