packages:
  all:
    compiler:: [gcc@13.4.0]
    providers:
      mpi:: [openmpi@4.1.8]
  mpi:
    buildable: False
  openmpi:
    buildable: False
    externals:
    - spec: openmpi@4.1.8 %gcc@=13.4.0
      # Note: slurm must be loaded before openmpi on Atlantis
      modules:
      - slurm
      - openmpi/4.1.8
