packages:
  all:
    compiler:: [gcc@13.4.0]
    providers:
      mpi:: [openmpi@5.0.6]
  mpi:
    buildable: False
  openmpi:
    buildable: False
    externals:
    - spec: openmpi@5.0.6 %gcc@13.4.0
      modules:
      - slurm
      - openmpi/5.0.6

