packages:
  all:
    require:
    - any_of: ['%llvm@=22.1.0']
      when: '%llvm'
  mpi:
    buildable: False
    require:
    - "openmpi@4.1.8"
  llvm:
    externals:
    - spec: llvm@22.1.0 +flang ~libomptarget
      prefix: /gpfs/neptune/spack-stack/llvm-22.1.0
      modules:
      - llvm/22.1.0
      extra_attributes:
        compilers:
          c: /gpfs/neptune/spack-stack/llvm-22.1.0/bin/clang
          cxx: /gpfs/neptune/spack-stack/llvm-22.1.0/bin/clang++
          fortran: /gpfs/neptune/spack-stack/llvm-22.1.0/bin/flang-new
        extra_rpaths:
        - /gpfs/neptune/spack-stack/llvm-22.1.0/lib
        - /gpfs/neptune/spack-stack/llvm-22.1.0/lib/x86_64-unknown-linux-gnu
  hwloc:
    buildable: False
    externals:
    - spec: hwloc@2.13.0
      prefix: /gpfs/neptune/spack-stack/llvm-22.1.0
  openmpi:
    externals:
    - spec: openmpi@4.1.8 ~internal-hwloc +two_level_namespace
      prefix: /gpfs/neptune/spack-stack/openmpi-4.1.8/llvm-22.1.0
      modules:
      - openmpi/4.1.8
