packages:
  all:
    compiler:: [gcc@13.4.0]
    providers:
      mpi:: [openmpi@4.1.8]
  mpi:
    buildable: False
  openmpi:
    buildable: False
    externals:
    - spec: openmpi@4.1.8 %gcc@=13.4.0
      prefix: /gpfs/neptune/spack-stack/openmpi-4.1.8/gcc-13.4.0
      modules:
      - openmpi/4.1.8
