packages:
  all:
    compiler:: [nvhpc@25.1, gcc@13.3.0]
    providers:
      mpi:: [openmpi@4.1.5]
      blas:: [nvhpc@25.1]
      zlib-api:: [zlib]
      fftw:: [nvhpc@25.1]
  mpi:
    buildable: False
  blas:
    buildable: False
  fckit:
    require: '~openmp'
  eckit:
    require: '~openmp'
  ecmwf-atlas:
    require: '~openmp ~fftw'
