packages:
  all:
    compiler:: [gcc@13.4.0]
    providers:
      mpi:: [openmpi@4.1.6]
  mpi:
    buildable: False
  openmpi:
    buildable: False
    externals:
    - spec: openmpi@4.1.6 ~cuda~cxx~cxx_exceptions~java~memchecker+pmi~static~wrapper-rpath
        fabrics=ucx schedulers=slurm
      prefix: /discover/swdev/gmao_SIteam/MPI/openmpi/4.1.6-SLES15/gcc-13.4.0
      modules:
      - mpi/openmpi/4.1.6/gcc-13.4.0
  gcc:
    buildable: false
    externals:
    - spec: gcc@13.4.0 languages='c,c++,fortran'
      prefix: /discover/swdev/gmao_SIteam/other/SLES15.4/GCC/13.4.0
      modules:
      - comp/gcc/13.4.0
      extra_attributes:
        compilers:
          c: /discover/swdev/gmao_SIteam/other/SLES15.4/GCC/13.4.0/bin/gcc
          cxx: /discover/swdev/gmao_SIteam/other/SLES15.4/GCC/13.4.0/bin/g++
          fortran: /discover/swdev/gmao_SIteam/other/SLES15.4/GCC/13.4.0/bin/gfortran
