packages:
  mpi:
    buildable: False
    require:
    - "intel-oneapi-mpi@2021.17"
  intel-oneapi-runtime:
    buildable: false
    externals:
    - spec: intel-oneapi-runtime@2025.3.0
      prefix: /opt/intel/oneapi
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2025.3.0
      prefix: /opt/intel/oneapi
      extra_attributes:
        compilers:
          c: /opt/intel/oneapi/2025.3/bin/icx
          cxx: /opt/intel/oneapi/2025.3/bin/icpx
          fortran: /opt/intel/oneapi/2025.3/bin/ifx
  gcc-runtime:
    buildable: false
    externals:
    - spec: gcc-runtime@11.5.0 %gcc@11.5.0
      prefix: /usr
  gcc:
    buildable: false
    externals:
    - spec: gcc@11.5.0 languages:='c,c++'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
  intel-oneapi-mpi:
    buildable: false
    externals:
    - spec: intel-oneapi-mpi@2021.17
      prefix: /opt/intel/oneapi
  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2025.3
      prefix: /opt/intel/oneapi
