packages:
  all:
    require:
    - any_of: ['%nvhpc@=26.5']
      when: '%nvhpc'
    - any_of: ['%gcc@=13.3.0']
      when: '%gcc'
  mpi:
    buildable: false
    require:
    - cray-mpich@8.1.32
  nvhpc:
    buildable: false
    externals:
    - spec: nvhpc@26.5+blas+lapack~mpi
      prefix: /p/app/projects/NEPTUNE/spack-stack/nvhpc-26.5
      modules:
      - PrgEnv-nvidia/8.7.0
      - nvhpc/26.5
      extra_attributes:
        compilers:
          c: /p/app/projects/NEPTUNE/spack-stack/nvhpc-26.5/Linux_x86_64/26.5/compilers/bin/nvc
          cxx: /p/app/projects/NEPTUNE/spack-stack/nvhpc-26.5/Linux_x86_64/26.5/compilers/bin/nvc++
          fortran: /p/app/projects/NEPTUNE/spack-stack/nvhpc-26.5/Linux_x86_64/26.5/compilers/bin/nvfortran
        environment:
          set:
            CONFIG_SITE: ''
  gcc:
    buildable: false
    externals:
    - spec: gcc@13.3.0 languages:='c,c++'
      prefix: /usr
      modules:
      - PrgEnv-gnu/8.7.0
      - gcc-native/13.2
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
        environment:
          set:
            CONFIG_SITE: ''
            PE_GCC_EXTERNAL: native
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.32
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/nvidia/23.3
      modules:
      - cray-mpich/8.1.32
      extra_attributes:
        environment:
          prepend_path:
            CMAKE_PREFIX_PATH: /p/app/projects/NEPTUNE/spack-stack/cmake-findmpi
