packages:
  all:
    require:
    - any_of: ['%intel-oneapi-compilers@=2026.0.0']
      when: '%intel-oneapi-compilers'
    - any_of: ['%gcc@=13.3.0']
      when: '%gcc'
  mpi:
    buildable: false
    require:
    - cray-mpich@8.1.32
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2026.0.0 +fix_rt_linkage
      prefix: /p/app/projects/NEPTUNE/spack-stack/oneapi-2026.0.0
      modules:
      - PrgEnv-intel/8.6.0
      - intel-oneapi/2026.0.0
      extra_attributes:
        compilers:
          c: /p/app/projects/NEPTUNE/spack-stack/oneapi-2026.0.0/2026.0/bin/icx
          cxx: /p/app/projects/NEPTUNE/spack-stack/oneapi-2026.0.0/2026.0/bin/icpx
          fortran: /p/app/projects/NEPTUNE/spack-stack/oneapi-2026.0.0/2026.0/bin/ifx
        environment:
          set:
            CONFIG_SITE: ''
  gcc:
    buildable: false
    externals:
    - spec: gcc@13.3.0 languages:='c,c++'
      prefix: /usr
      modules:
      - PrgEnv-gnu/8.6.0
      - gcc-native/13.2
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
        environment:
          set:
            CONFIG_SITE: ''
            PE_GCC_EXTERNAL: native
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.32
      prefix: /opt/cray/pe/mpich/8.1.32/ofi/INTEL/2022.1
      modules:
      - libfabric/2.3.1
      - craype-network-ofi
      - cray-mpich/8.1.32
      extra_attributes:
        environment:
          prepend_path:
            CMAKE_PREFIX_PATH: /p/app/projects/NEPTUNE/spack-stack/cmake-findmpi
  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2026.0
      prefix: /p/app/projects/NEPTUNE/spack-stack/oneapi-2026.0.0
