packages:
  mpi:
    buildable: False
    require:
    - "cray-mpich@8.1.32"
  gcc:
    externals:
    - spec: gcc@13.3.0 languages:='c,c++,fortran'
      prefix: /usr
      modules:
      - PrgEnv-gnu/8.6.0
      - gcc-native/13.2
      - libfabric/1.22.0
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
        environment:
          prepend_path:
            LD_LIBRARY_PATH: '/opt/cray/libfabric/1.22.0/lib64'
          set:
            CONFIG_SITE: ''
            CRAY_CPU_TARGET: x86-genoa
  gcc-runtime:
    externals:
    - spec: gcc-runtime@13.3.0
      prefix: /usr
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.32%gcc@13.3.0 ~wrappers
      modules:
      - cray-mpich/8.1.32
      - craype-network-ofi
