packages:
  autoconf:
    externals:
    - spec: autoconf@2.72
      prefix: /Users/mathomp4/.homebrew/brew
  automake:
    externals:
    - spec: automake@1.18.1
      prefix: /Users/mathomp4/.homebrew/brew
  bash:
    externals:
    - spec: bash@5.3.3
      prefix: /Users/mathomp4/.homebrew/brew
  cmake:
    externals:
    - spec: cmake@4.1.1
      prefix: /Users/mathomp4/.homebrew/brew
  cvs:
    externals:
    - spec: cvs@1.12.13
      prefix: /Users/mathomp4/.homebrew/brew
  doxygen:
    externals:
    - spec: doxygen@1.14.0+graphviz~mscgen
      prefix: /Users/mathomp4/.homebrew/brew
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.3.1
      prefix: /Users/mathomp4/.homebrew/brew
  git:
    externals:
    - spec: git@2.51.0+tcltk
      prefix: /Users/mathomp4/.homebrew/brew
    - spec: git@2.50.1~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.7.0
      prefix: /Users/mathomp4/.homebrew/brew
  groff:
    externals:
    - spec: groff@1.23.0
      prefix: /Users/mathomp4/.homebrew/brew
  libtool:
    externals:
    - spec: libtool@2.5.4
      prefix: /Users/mathomp4/.homebrew/brew
  ninja:
    externals:
    - spec: ninja@1.13.1
      prefix: /Users/mathomp4/.homebrew/brew
  npm:
    externals:
    - spec: npm@11.6.0
      prefix: /Users/mathomp4/.homebrew/brew
  openssh:
    externals:
    - spec: openssh@9.9p2
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.42.0~cpanm+opcode+open+shared+threads
      prefix: /Users/mathomp4/.homebrew/brew
    - spec: perl@5.34.1~cpanm+opcode+open+shared+threads
      prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@2.5.1
      prefix: /Users/mathomp4/.homebrew/brew
  rust:
    externals:
    - spec: rust@1.90.0
      prefix: /Users/mathomp4/.homebrew/brew
      extra_attributes:
        cargo: /Users/mathomp4/.homebrew/brew/bin/cargo
        compilers:
          rust: /Users/mathomp4/.homebrew/brew/bin/rustc
  subversion:
    externals:
    - spec: subversion@1.14.5
      prefix: /Users/mathomp4/.homebrew/brew
  swig:
    externals:
    - spec: swig@4.3.1
      prefix: /Users/mathomp4/.homebrew/brew
  tar:
    externals:
    - spec: tar@1.35
      prefix: /Users/mathomp4
  tcsh:
    externals:
    - spec: tcsh@6.24.16
      prefix: /Users/mathomp4/.homebrew/brew
  texinfo:
    externals:
    - spec: texinfo@7.2
      prefix: /Users/mathomp4/.homebrew/brew
