packages:
  c:
    require: [apple-clang@17.0.0]
  cxx:
    require: [apple-clang@17.0.0]
  fortran:
    require: [gcc@15.2.0]
  mpi:
    require: [openmpi@=5.0.10]
  apple-clang:
    externals:
    - spec: apple-clang@17.0.0 languages:='c,c++'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang
          cxx: /usr/bin/clang++
  gcc:
    buildable: False
    externals:
    - spec: gcc@15.2.0 languages:='fortran'
      prefix: /Users/mathomp4/.homebrew/brew
      extra_attributes:
        compilers:
          fortran: /Users/mathomp4/.homebrew/brew/bin/gfortran-15
