packages:
  all:
    compiler:: [gcc@12.4.0]
    providers:
      mpi:: [cray-mpich@8.1.29]
  mpi:
    buildable: False
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.29%gcc@12.4.0 +wrappers
      modules:
      - craype/2.7.31
      - ncarenv/24.12
      - cray-mpich/8.1.29
      - libfabric/1.15.2.0
      environment:
        prepend_path:
          PATH: '/opt/cray/pe/pals/1.2.12/bin'
          PKG_CONFIG_PATH: '/opt/cray/pe/pals/1.2.12/lib/pkgconfig'
          MANPATH: '/opt/cray/pe/pals/1.2.12/man'
          PE_PALS_PKGCONFIG_LIBS: 'libpals'
          PE_PKGCONFIG_PRODUCTS: 'PE_PALS'
        set:
          # https://github.com/JCSDA/spack-stack/issues/957
          FI_CXI_RX_MATCH_MODE: 'hybrid'
          # https://github.com/JCSDA/spack-stack/issues/1012
          I_MPI_EXTRA_FILESYSTEM: 'ON'
          I_MPI_OFI_LIBRARY: '/opt/cray/libfabric/1.15.2.0/lib64/libfabric.so.1'
        extra_rpaths: []

