packages:
  mpi:
    buildable: False
    require: cray-mpich@8.1.29
  cray-mpich:
    buildable: False
    externals:
    - spec: cray-mpich@8.1.29 +wrappers
      prefix: /opt/cray/pe/mpich/8.1.29/ofi/gnu/12.3
      modules:
      - ncarenv/24.12
      - craype/2.7.31
      - cray-mpich/8.1.29
      - libfabric/1.15.2.0
      - cray-pals/1.2.11
  gcc:
    buildable: False
    externals:
    - spec: gcc@12.4.0 languages:='c,c++'
      prefix: /glade/u/apps/casper/24.12/spack/opt/spack/gcc/12.4.0/5b5c
      modules:
      - ncarenv/24.12
      - gcc/12.4.0
      extra_attributes:
        compilers:
          c: /glade/u/apps/casper/24.12/spack/opt/spack/gcc/12.4.0/5b5c/bin/gcc
          cxx: /glade/u/apps/casper/24.12/spack/opt/spack/gcc/12.4.0/5b5c/bin/g++
          fortran: /glade/u/apps/casper/24.12/spack/opt/spack/gcc/12.4.0/5b5c/bin/gfortran
        environment:
          prepend_path:
            # For compiling scotch (which requires Intel MPI) with gcc in the oneapi@2024.2.1 unified environment
            LD_LIBRARY_PATH: '/glade/u/apps/casper/24.12/spack/opt/spack/intel-oneapi-compilers/2024.2.1/gcc/12.4.0/iq3b/compiler/2024.2/lib'
          set:
            # https://github.com/JCSDA/spack-stack/issues/957
            FI_CXI_RX_MATCH_MODE: 'hybrid'
        extra_rpaths: []

