mirrors:
  local-source:
    url: file:///swbuild/gmao_SIteam/spack-stack/source-cache
    binary: false
  local-binary:
    url: file:///swbuild/gmao_SIteam/spack-stack/build-cache
    binary: true

