packages:
  all:
    require:
    - any_of: ['%gcc@=14.2.1']
      when: '%gcc'
  mpi:
    buildable: false
    require:
    - "cray-mpich@8.1.33"
  gcc:
    buildable: false
    externals:
    - spec: gcc@14.2.1 languages:='c,c++,fortran'
      prefix: /opt/rh/gcc-toolset-14/root/usr
      modules:
      - cray-libpals/1.7.1
      - cray-pals/1.7.1
      - craype-x86-turin
      - libfabric/12.0
      - craype-network-ofi
      - cray-dsmml/0.3.1
      - PrgEnv-gnu/8.6.0
      - gcc-native/14
      extra_attributes:
        compilers:
          c: /opt/rh/gcc-toolset-14/root/usr/bin/gcc
          cxx: /opt/rh/gcc-toolset-14/root/usr/bin/g++
          fortran: /opt/rh/gcc-toolset-14/root/usr/bin/gfortran
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.33
      prefix: /opt/cray/pe/mpich/8.1.33/ofi/gnu/11.2
      modules:
      - cray-libpals/1.7.1
      - cray-pals/1.7.1
      - craype-x86-turin
      - libfabric/12.0
      - craype-network-ofi
      - cray-dsmml/0.3.1
      - cray-mpich/8.1.33
      - mpi/mpich-gfortran
      extra_attributes:
        environment:
          set:
            MPICH_CC: gcc
            MPICH_CXX: g++
            MPICH_FC: gfortran
            CC: gcc
            CXX: g++
            FC: gfortran

  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2024.2
      prefix: /nasa/intel/oneapi-test

  # Testing shows we now need to pass in -lm for GCC
  p4est:
    require:
    - 'ldflags="-lm"'
