packages:
  #
  ### Compilers
  #
  fortran:
    # without this I had some weird concretization; no fortran deps require gcc
    require: 'intel-oneapi-compilers'
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2024.2.1 ~envmods
      modules:
      - PrgEnv-intel/8.3.3
      - craype/2.7.17
      - intel-oneapi/2024.2
      - libfabric
      extra_attributes:
        compilers:
          c: cc
          cxx: CC
          fortran: ftn
        flags:
          cflags: '--gcc-toolchain=/opt/cray/pe/gcc/12.1.0/snos'
          cxxflags: '--gcc-toolchain=/opt/cray/pe/gcc/12.1.0/snos'
          fflags: '-gcc-name=/opt/cray/pe/gcc/12.1.0/snos/bin/gcc -gxx-name=/opt/cray/pe/gcc/12.1.0/snos/bin/g++'
        environment:
          prepend_path:
            PATH: /opt/cray/pe/gcc/12.1.0/snos/bin
            LD_LIBRARY_PATH: /opt/cray/pe/gcc/12.1.0/snos/lib64
            LIBRARY_PATH: /opt/cray/pe/gcc/12.1.0/snos/lib64
            CPATH: /opt/cray/pe/gcc/12.1.0/snos/include
          set:
            CONFIG_SITE: ''
            PYTHONPATH: ''
            INTEL_COMPILER_TYPE: RECOMMENDED
          unset: [PYTHONPATH]
  gcc:
    buildable: false
    externals:
    - spec: gcc@12.1.0 languages:='c,c++,fortran'
      prefix: /opt/cray/pe/gcc/12.1.0/snos/
      extra_attributes:
        compilers:
          c: /opt/cray/pe/gcc/12.1.0/snos/bin/gcc
          cxx: /opt/cray/pe/gcc/12.1.0/snos/bin/g++
          fortran: /opt/cray/pe/gcc/12.1.0/snos/bin/gfortran
        environment:
          set:
            CONFIG_SITE: ''
            PYTHONPATH: ''
  gcc-runtime:
    require: '%gcc@12.1.0'
  #
  ### MPI external
  #
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.29~wrappers
      prefix: /opt/cray/pe/mpich/8.1.29/ofi/intel/2022.1
      modules:
      - libfabric
      - craype-network-ofi
      - cray-mpich/8.1.29
      - cray-pals
  #
  ### Individual package settings
  #
  apr:
    require: ['@:1.6', '%gcc']
  bison:
    require: ['%gcc']
  cairo:
    require: ['+fc']
  cmake:
    require: ['%gcc']
  ecflow:
    require::
    - '@5.11.4'
    - '+ui'
  eckit:
    require:: ['@:']
  ectrans:
    require:: ['@1.2.0', '+fftw']
  elfutils:
    require: ['@0.191']
  fckit:
    require:: ['@:', '+eckit']
  gdal:
    require:: ['~curl']
  glib:
    require: ['%gcc']
  gsibec:
    require: ['@1.4.2']
  harfbuzz:
    require:
    - any_of: ['@:2.9 %gcc', '@11: %oneapi']
  libtiff:
    require: ['build_system=cmake']
  nco:
    require:: ['%oneapi']
  ninja:
    require: ['~re2c %gcc']
  pixman:
    require: ['build_system=meson']
  proj:
    require: ['@9.4.1']
  py-numpy::
    require:: ['@1.26']
  subversion:
    require: ['%gcc']
  zlib-ng:
    require: ['cflags="-static-intel"', 'cxxflags="-static-intel"']
