packages:
  # Don't build compilers
  c:
    buildable: false
  cxx:
    buildable: false
  fortran:
    buildable: false
  #
  ### Providers
  #
  blas:
    require:: ['openblas']
  fftw-api:
    require: ['fftw']
  jpeg:
    require: ['libjpeg-turbo']
  lapack:
    require:: ['openblas']
  mkl:
    buildable: false
  mpi:
    buildable: false
    require: ['cray-mpich']
  #
  ### Individual package settings
  #
  # Use `require::` to override require's from common/packages.yaml,
  # and `require:<newline>  - '...'` to add to existing ones.
  bacio:
    require:: ['@2.4.1']
  boost:
    require:: ['@:']
  cdo:
    require: ['grib2=none']
  crtm:
    require: ['+fix']
  curl:
    require: ['~nghttp2']
  ecmwf-atlas:
    require:: ['+fckit', '~trans', '~fftw']
  ectrans:
    require:: ['+fftw']
  flex:
    require: ['@2.6.4']
  gdal:
    variants: ~curl
  icu4c:
    require: ['%gcc']
  libxslt:
    require: ['~crypto']
  mapl:
    require:: ['@2.53', '~pflogger', '~fargparse', '~extdata2g']
  nco:
    require:: ['%oneapi']
  netcdf-c:
    require:: ['@4.9.2', '+mpi', '~parallel-netcdf', '~dap', '~blosc', '~szip']
  py-pandas:
    require:: ['~excel']
  scotch:
    require::
      - '@7.0.7'
      - +mpi
      - +metis
      - ~shared
      - ~threads
      - ~mpi_thread
      - +noarch
      - +esmumps
      - build_system=cmake
  subversion:
    require: ['~serf', '+pic']
  zlib-ng:
    require: ['+compat', '~new_strategies']
