packages:
  all:
    compiler:: [intel@2023.2.0]
    providers:
      mpi:: [cray-mpich@8.1.30]
      # Remove the next three lines to switch to intel-oneapi-mkl
      blas:: [openblas]
      fftw-api:: [fftw]
      lapack:: [openblas]

### MPI, Python, MKL
  mpi:
    buildable: False
  cray-mpich:
    externals:
    - spec: cray-mpich@8.1.30%intel@2023.2.0~wrappers
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/intel/2022.1
      modules:
      - craype-network-ofi
      - cray-mpich/8.1.30
  intel-oneapi-mkl:
    buildable: False

### Modification of common packages
  bison:
    require:
    - '%gcc'
  ectrans:
    require::
    - '@1.2.0 ~mkl +fftw'
  gsibec:
    require::
    - '@1.2.1 ~mkl'
  py-numpy:
    require::
    - '@1.26'
    - '^openblas'
