name: Nightly 03 Setup Unified Env

runs:
  using: "composite"
  steps:
  - name: Nightly 03 Setup Unified Env
    shell: bash
    run: |
      RUNID=`date +"%Y%m%d"`
      cd util/weekly_build
      ./03_SetupEnv.sh ${RUNID} ${BASEDIR} ${PLATFORM}
