packages:
  all:
    require:
    - any_of: ['%intel-oneapi-compilers@=2024.2.0']
      when: '%intel-oneapi-compilers'
    - any_of: ['%gcc@=13.3.0']
      when: '%gcc'
  mpi:
    buildable: false
    require:
    - cray-mpich@8.1.30
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2024.2.0 +fix_rt_linkage
      prefix: /opt/intel/oneapi_2024.2.0.634
      modules:
      - PrgEnv-intel/8.5.0
      - intel-oneapi/2024.2
      extra_attributes:
        compilers:
          c: /opt/intel/oneapi_2024.2.0.634/compiler/2024.2/bin/icx
          cxx: /opt/intel/oneapi_2024.2.0.634/compiler/2024.2/bin/icpx
          fortran: /opt/intel/oneapi_2024.2.0.634/compiler/2024.2/bin/ifort
        environment:
          set:
            CONFIG_SITE: ''
            # Force ifort not ifx
            INTEL_COMPILER_TYPE: 'RECOMMENDED'
  gcc:
    buildable: false
    externals:
    - spec: gcc@13.3.0 languages:='c,c++,fortran'
      prefix: /usr
      modules:
      - PrgEnv-gnu/8.5.0
      - gcc-native/13.2
      extra_attributes:
        compilers:
          c: /usr/bin/gcc-13
          cxx: /usr/bin/g++-13
          fortran: /usr/bin/gfortran-13
        environment:
          set:
            CONFIG_SITE: ''
            PE_GCC_EXTERNAL: native
        extra_rpaths:
        - /opt/cray/libfabric/1.22.0/lib64
  cray-mpich:
    buildable: false
    externals:
    - spec: cray-mpich@8.1.30
      prefix: /opt/cray/pe/mpich/8.1.30/ucx/intel/2022.1
      modules:
      - cray-mpich-ucx/8.1.30
      extra_attributes:
        extra_rpaths:
        - /opt/cray/libfabric/1.22.0/lib64
  intel-oneapi-mkl:
    buildable: false
    externals:
    - spec: intel-oneapi-mkl@2024.2
      prefix: /opt/intel/oneapi_2024.2.0.634
