packages:
  intel:
    externals:
    - spec: intel@2021.13.1
      prefix: /p/app/unsupported/intel/oneapi/2024.2.1/compiler/2024.2
      extra_attributes:
        compilers:
          fortran: /p/app/unsupported/intel/oneapi/2024.2.1/compiler/2024.2/bin/ifort
  binutils:
    externals:
    - spec: binutils@2.38.17~gold~headers
      prefix: /opt/rh/gcc-toolset-12/root/usr
  openssh:
    externals:
    - spec: openssh@9.9p2a
      prefix: /usr/local/krb5
  rdma-core:
    externals:
    - spec: rdma-core@56.0
      prefix: /usr
  zlib:
    externals:
    - spec: zlib@1.2.11
      prefix: /usr
  intel-oneapi-compilers:
    externals:
    - spec: intel-oneapi-compilers@2024.2.1
      prefix: /p/app/unsupported/intel/oneapi/2024.2.1/compiler/2024.2
      extra_attributes:
        compilers:
          c: /p/app/unsupported/intel/oneapi/2024.2.1/compiler/2024.2/bin/icx
          cxx: /p/app/unsupported/intel/oneapi/2024.2.1/compiler/2024.2/bin/icpx
          fortran: /p/app/unsupported/intel/oneapi/2024.2.1/compiler/2024.2/bin/ifx
