packages:
  # Don't build compilers
  c:
    buildable: false
  cxx:
    buildable: false
  fortran:
    buildable: false
  #
  ### Providers
  #
  blas:
    require:: ['openblas']
  fftw-api:
    require: ['fftw']
  jpeg:
    require: ['libjpeg-turbo']
  lapack:
    require:: ['openblas']
  mkl:
    buildable: false
  mpi:
    buildable: false
    require: ['cray-mpich']
  #
  ### Individual package settings
  #
  curl:
    require: ['~nghttp2']
  flex:
    require: ['@2.6.4']
  gdal:
    require: ['~curl']
  global-workflow-env:
    require:: ['~uwtools']
  icu4c:
    require: ['%gcc']
  libxslt:
    require: ['~crypto']
  nco:
    require:: ['%oneapi']
  py-pandas:
    require:: ['~excel']
  subversion:
    require: ['~serf', '+pic']
  zlib-ng:
    require: ['+compat', '~new_strategies']
