mirrors:
  local-source: file:///scratch4/NCEPDEV/nems/Dom.Heinzeller/spack-stack-automation/source-cache
  local-binary: file:///scratch4/NCEPDEV/nems/Dom.Heinzeller/spack-stack-automation/build-cache
