packages:
  mpi:
    buildable: False
    require:
    - intel-oneapi-mpi@2021.13
  intel-oneapi-runtime:
    buildable: False
    externals:
    - spec: intel-oneapi-runtime@2025.2.1
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-compilers-2025.2.1-5nijquf65qj5mmbn3k2gxkjkrjkpjtw7
  intel-oneapi-compilers:
    buildable: False
    externals:
    - spec: intel-oneapi-compilers@2025.2.1
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-compilers-2025.2.1-5nijquf65qj5mmbn3k2gxkjkrjkpjtw7
      modules:
      - intel-oneapi-compilers/2025.2.1
      extra_attributes:
        compilers:
          c: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-compilers-2025.2.1-5nijquf65qj5mmbn3k2gxkjkrjkpjtw7/compiler/2025.2/bin/icx
          cxx: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-compilers-2025.2.1-5nijquf65qj5mmbn3k2gxkjkrjkpjtw7/compiler/2025.2/bin/icpx
          fortran: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-compilers-2025.2.1-5nijquf65qj5mmbn3k2gxkjkrjkpjtw7/compiler/2025.2/bin/ifx
        environment:
          prepend_path:
            LD_LIBRARY_PATH: '/usr/lib:/usr/lib64'
            PATH: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/bin
            CPATH: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/include 
        extra_rpaths:
        - /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/lib
        - /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/lib64
  intel-oneapi-mpi:
    buildable: False
    externals:
    - spec: intel-oneapi-mpi@2021.13
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/oneapi-2024.2.1/intel-oneapi-mpi-2021.13.1-ss72gbndvat3oz22sa6lhmlbjkeabrn4
      modules:
      - intel-oneapi-mpi/2021.13.1
  intel-oneapi-mkl:
    buildable: False
    externals:
    - spec: intel-oneapi-mkl@2024.2
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-oneapi-mkl-2024.2.1-srqwrbzwo2k7hxuuhlrxttburs5jvlat
      modules:
      - intel-oneapi-mkl/2024.2.1
  intel-oneapi-tbb:
    buildable: False
    externals:
    - spec: intel-oneapi-tbb@2021.12
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/intel-tbb-2021.12.0-grcsmccjpm3trn6rgtyq76kdxks6ygzm
  gcc-runtime:
    buildable: False
    externals:
    - spec: gcc-runtime@12.4.0
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj
  gcc:
    buildable: False
    externals:
    - spec: gcc@12.4.0 languages:='c,c++'
      prefix: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj
      modules:
      - gcc/12.4.0
      extra_attributes:
        compilers:
          c: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/bin/gcc
          cxx: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/bin/g++
          fortran: /apps/spack-2024-12/linux-rocky9-x86_64/gcc-11.4.1/gcc-12.4.0-dsgnou52lpn2tus6mohdmcw5mjqmqrhj/bin/gfortran
