modules:
  default:
    enable::
    - tcl
    tcl:
      include:
      # List of packages for which we need modules that are blacklisted by default
      # Compiler
      - apple-clang
      - gcc
      - intel-oneapi-compilers
      - llvm
      # MPI
      - cray-mpich
      - intel-mpi
      - intel-oneapi-mpi
      - mpich
      - mpt
      - openmpi
