spack:
  concretizer:
    unify: true

  config:
    checksum: false
    build_jobs: 4
    connect_timeout: 60

  compilers:
  - compiler:
      spec: gcc@11.4.0
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: ubuntu24.04
      modules: []
      environment: {}
      extra_rpaths: []

  # Basic package config from configs/common/packages.yaml
  # Additional package config for container
  packages:
    all:
      prefer:
      - '%gcc'
      target: [x86_64]
      providers:
        mpi: [openmpi@5.0.8]

    # Compilers and meta packages.
    gcc:
      buildable: false
      externals:
      - spec: gcc@11.4.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
    gcc-runtime:
      buildable: false
      externals:
      - spec: gcc-runtime@11.4.0
        prefix: /usr
    mpi:
      require: [openmpi@5.0.8]

    diffutils:
      buildable: false
      externals:
      - spec: diffutils@3.10
        prefix: /usr
    git:
      buildable: false
      externals:
      - spec: git@2.43.0~tcltk
        prefix: /usr
    git-lfs:
      buildable: false
      externals:
      - spec: git-lfs@3.4.1
        prefix: /usr
    llvm:
      buildable: false
      externals:
      - spec: llvm@14.0.6
        prefix: /usr
    mysql:
      buildable: false
      externals:
      - spec: mysql@8.0.40
        prefix: /usr
    qt:
      buildable: false
      externals:
      - spec: qt@5.15.3
        prefix: /usr
      version: [5.15.3]
    wget:
      buildable: false
      externals:
      - spec: wget@1.21.4
        prefix: /usr
    perl:
      buildable: false
      externals:
      - spec: perl@5.38.2
        prefix: /usr

  specs: []

  container:

    # Select the format of the recipe e.g. docker,
    # singularity or anything else that is currently supported
    format: docker

    images:
      os: ubuntu:24.04
      spack:
        url: https://github.com/jcsda/spack
        ref: spack-stack-dev
        resolve_sha: true

    # Whether or not to strip binaries
    strip: false

    ## Additional system packages that are needed at runtime
    os_packages:
      build:
      - bc
      - cpp-11
      - g++-11
      - gcc-11
      - gfortran-11
      - git
      - git-lfs
      - llvm-14
      - make
      - mysql-server
      - qtbase5-dev
      - qt5-qmake
      - libqt5svg5-dev
      - qt5dxcb-plugin
      - wget

      final:
      - bc
      - cpp-11
      - g++-11
      - gcc-11
      - gfortran-11
      - git
      - git-lfs
      - llvm-14
      - make
      - mysql-server
      - qtbase5-dev
      - qt5-qmake
      - libqt5svg5-dev
      - qt5dxcb-plugin
      - wget
      - ca-certificates
      - curl
      - file
      - gnupg2
      - iproute2
      - locales
      - unzip
      - vim
      - nano
      - less

    # Extra instructions
    extra_instructions:
      pre_build: |
        # Register spack-stack extension repo
        RUN spack repo add $SPACK_ROOT/var/spack/repos/spack-stack --scope defaults && \
        update-alternatives --remove-all cpp && \
        update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-11 100 && \
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100 && \
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && \
        update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-11 100 && \
        # Needed by py-llvmlite
        update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 100
      pre_final: |
        # Set environment variables for installing tzdata
        ENV DEBIAN_FRONTEND=noninteractive
        ENV TZ=Etc/UTC
        ENV CC=gcc
        ENV CXX=g++
        ENV FC=gfortran
      build: |
        # Put output of spack find into a file
        RUN cd /opt/spack-environment && \
        spack env activate -d . && \
        spack find 2>&1 | tee /root/spack_find.out
      final: |
        # Copy spack find output from builder
        COPY --from=builder /root/spack_find.out /root/spack_find.out
        # Set compiler defaults.
        RUN update-alternatives --install /usr/bin/cpp cpp /usr/bin/cpp-11 100 && \
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100 && \
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 && \
        update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-11 100 && \
        # Needed by py-llvmlite
        update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 100 && \
        # Make a non-root user:nonroot / group:nonroot for running MPI
        useradd -U -k /etc/skel -s /bin/bash -d /home/nonroot -m nonroot --uid 43891 && \
        # Set startup environment variables not set by spack.
        echo "ulimit -s unlimited" >> /etc/spack_container_rc.sh && \
        echo "ulimit -v unlimited" >> /etc/spack_container_rc.sh && \
        echo "export CC=gcc" >> /etc/spack_container_rc.sh && \
        echo "export CXX=g++" >> /etc/spack_container_rc.sh && \
        echo "export FC=gfortran" >> /etc/spack_container_rc.sh && \
        # Set necessary environment variables and config for openmpi.
        echo "export OMPI_ALLOW_RUN_AS_ROOT=1" >> /etc/spack_container_rc.sh && \
        echo "export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1" >> /etc/spack_container_rc.sh && \
        echo "export PRTE_MCA_rmaps_default_mapping_policy=:oversubscribe" >> /etc/spack_container_rc.sh && \
        echo "export jedi_cmake_ROOT=$(ls -d /opt/software/linux-*/jedi-cmake-*)" >> /etc/spack_container_rc.sh && \
        echo "source /etc/spack_container_rc.sh" >> /etc/bash.bashrc && \
        # More openmpi config.
        mkdir -p /root/.pmix && \
        echo "rmaps_default_mapping_policy=:oversubscribe" >> /root/.pmix/mca-params.conf && \
        mkdir -p /home/nonroot/.pmix && \
        echo "rmaps_default_mapping_policy=:oversubscribe" >> /home/nonroot/.pmix/mca-params.conf && \
        chown -R nonroot:nonroot /home/nonroot/.gitconfig /home/nonroot/.pmix && \
        # Git config settings.
        printf "[credential]\n    helper = cache --timeout=7200\n" >> /home/nonroot/.gitconfig && \
        printf "[credential]\n    helper = cache --timeout=7200\n" >> /root/.gitconfig

        # Ensure that the container rc is run by non-login shells.
        ENV BASH_ENV=/etc/spack_container_rc.sh

    # Labels for the image
    labels:
      app: ""
      mpi: "openmpi"
