spack:
  concretizer:
    unify: true

  config:
    checksum: false
    build_jobs: 2
    connect_timeout: 60

  # Basic package config from configs/common/packages.yaml
  # Additional package config for container
  packages:
    all:
      prefer:
      - '%oneapi'
      target: [x86_64]
      providers:
        mpi: [intel-oneapi-mpi@2021.13]

    # Compilers and meta packages.
    intel-oneapi-compilers:
      buildable: false
      externals:
      - spec: intel-oneapi-compilers@2025.3.0
        prefix: /opt/intel/oneapi
        modules:
        - umf/1.0.2
        - tbb/2022.3
        - compiler-rt/2025.3.0
        - compiler/2025.3.0
        extra_attributes:
          compilers:
            fortran: /opt/intel/oneapi/compiler/2025.3/bin/ifx
            c: /opt/intel/oneapi/compiler/2025.3/bin/icx
            cxx: /opt/intel/oneapi/compiler/2025.3/bin/icpx
    gcc:
      externals:
      - spec: gcc@13.3.0 languages:='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
      buildable: false
    intel-oneapi-mkl:
      buildable: false
      externals:
      - spec: intel-oneapi-mkl@2025.3
        prefix: /opt/intel/oneapi
        modules:
        - mkl/2025.3
    intel-oneapi-mpi:
      buildable: false
      externals:
      - spec: intel-oneapi-mpi@2021.17
        modules:
        - mpi/2021.17
        prefix: /opt/intel/oneapi
    intel-oneapi-tbb:
      buildable: false
      externals:
      - spec: intel-oneapi-tbb@2022.3
        prefix: /opt/intel/oneapi
        modules:
        - tbb/2022.3
    mpi:
      require: [intel-oneapi-mpi@2021.17]
    mpich:
      buildable: false
    mkl:
      require: [intel-oneapi-mkl@2025.3]
    openmpi:
      buildable: false

    # System packages and spack package requirements.
    autoconf:
      externals:
      - spec: autoconf@2.71
        prefix: /usr
    automake:
      externals:
      - spec: automake@1.16.5
        prefix: /usr
    binutils:
      externals:
      - spec: binutils@2.38
        prefix: /usr
    bison:
      require:
      - '%gcc'
    coreutils:
      externals:
      - spec: coreutils@8.32
        prefix: /usr
    ectrans:
      require:
      - '+mkl ~fftw'
    git:
      buildable: false
      externals:
      - spec: git@2.43.0~tcltk
        prefix: /usr
    git-lfs:
      buildable: false
      externals:
      - spec: git-lfs@3.4.1
        prefix: /usr
    gmake:
      externals:
      - spec: gmake@4.3
        prefix: /usr
    # Building icu4c with oneapi intel causes segfault.
    icu4c:
      require:
      - '%gcc'
    libmd:
      require:
      - '%gcc'
    libbsd:
      require:
      - '%gcc'
    llvm:
      buildable: false
      externals:
      - spec: llvm@14.0.6
        prefix: /usr
    mysql:
      buildable: false
      externals:
      - spec: mysql@8.0.40
        prefix: /usr
    pkg-config:
      externals:
      - spec: pkg-config@0.29.2
        prefix: /usr
    py-pynacl:
      buildable: false
      externals:
      - spec: py-pynacl@1.5.0
        prefix: /usr
    py-numpy:
      require:
      - '^intel-oneapi-mkl'
    qt:
      buildable: false
      externals:
      - spec: qt@5.15.3
        prefix: /usr
      version: [5.15.3]
    sp:
      require:
      - +pic

  specs: []

  container:

    # Select the format of the recipe e.g. docker,
    # singularity or anything else that is currently supported
    format: docker

    # Sets the base images for the stages where Spack builds and installs.
    images:
      os: ubuntu:24.04
      spack:
        url: https://github.com/jcsda/spack
        ref: spack-stack-dev
        resolve_sha: true

    # Whether or not to strip binaries
    strip: false

    ## Additional system packages that are needed at runtime
    os_packages:
      build:
      - autoconf
      - automake
      - autopoint
      - bc
      - cpp-13
      - cmake
      - flex
      - g++-13
      - gcc-13
      - gettext
      - gfortran-13
      - git
      - git-lfs
      - gpg
      - libgomp1
      - llvm-14
      - mysql-server
      - pkg-config
      - qtbase5-dev
      - qt5-qmake
      - libqt5svg5-dev
      - qt5dxcb-plugin
      - libcurl4-openssl-dev
      - wget
      - environment-modules

      final:
      - autopoint
      - bc
      - cpp-13
      - g++-13
      - gcc-13
      - gettext
      - gfortran-13
      - git
      - git-lfs
      - gpg
      - libgomp1
      - llvm-14
      - make
      - mysql-server
      - pkg-config
      - qtbase5-dev
      - qt5-qmake
      - libqt5svg5-dev
      - qt5dxcb-plugin
      - libcurl4-openssl-dev
      - wget
      # Implicitly included in build step
      - build-essential
      - ca-certificates
      - curl
      - file
      - gnupg2
      - iproute2
      - locales
      - python3
      - python3-pip
      - python3-setuptools
      - unzip
      - vim
      - nano
      - less
      - environment-modules

    # Extra instructions
    extra_instructions:
      pre_build: |
        RUN apt update && apt install apt-utils && \
            wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null && \
            echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list && \
            apt update && \
            apt install intel-oneapi-compiler-dpcpp-cpp-2025.3 \
                        intel-oneapi-compiler-fortran-2025.3 \
                        intel-oneapi-mpi-devel-2021.17 \
                        intel-oneapi-tbb-devel-2022.3 \
                        intel-oneapi-mkl-devel-2025.3 -y && \
        echo 'source /etc/profile.d/modules.sh && module use /opt/intel/oneapi/modulefiles' > /etc/profile.d/z01_oneapi_modules.sh && \
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100 && \
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 && \
        update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-13 100 && \
        rm /usr/bin/cpp && ln -s /usr/bin/cpp-13 /usr/bin/cpp && \
        # Needed by py-llvmlite
        update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 100 && \
        rm -rf /var/lib/apt/lists/*
        # BASH_ENV is used by the docker build system. Run commands will source this file prior to executing the command.
        ENV BASH_ENV=/etc/profile.d/z01_oneapi_modules.sh
      pre_final: |
        # Set environment variables for installing tzdata
        ENV DEBIAN_FRONTEND=noninteractive
        ENV TZ=Etc/UTC
        ENV CC=icx
        ENV CXX=icpx
        ENV FC=ifort
      build: |
        # Put output of spack find into a file
        RUN cd /opt/spack-environment && \
        spack env activate -d . && \
        spack find 2>&1 | tee /root/spack_find.out && \
        spack spec > /root/spack_spec.out
      final: |
        # Install Intel compilers and MPI library and pynacl
        RUN apt update && apt install apt-utils && \
            wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null && \
            echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list && \
            apt update && \
            apt install intel-oneapi-compiler-dpcpp-cpp-2025.3 \
                        intel-oneapi-compiler-fortran-2025.3 \
                        intel-oneapi-mpi-devel-2021.17 \
                        intel-oneapi-tbb-devel-2022.3 \
                        intel-oneapi-mkl-devel-2025.3 -y && \
        echo 'source /etc/profile.d/modules.sh && module use /opt/intel/oneapi/modulefiles' > /etc/profile.d/z01_oneapi_modules.sh
        RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100 && \
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 && \
        update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-13 100 && \
        rm /usr/bin/cpp && ln -s /usr/bin/cpp-13 /usr/bin/cpp && \
        # Needed by py-llvmlite
        update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-14 100 && \
        rm -rf /var/lib/apt/lists/* && \
        /opt/views/view/bin/pip3 install pynacl
        # Copy spack find output from builder
        COPY --from=builder /root/spack_find.out /root/spack_find.out
        # Make a non-root user:nonroot / group:nonroot for running MPI
        RUN useradd -U -k /etc/skel -s /bin/bash -d /home/nonroot -m nonroot --uid 43891 && \
        echo "source /etc/profile.d/z01_oneapi_modules.sh" > /etc/spack_container_rc.sh  && \
        echo "ulimit -s unlimited" >> /etc/spack_container_rc.sh  && \
        echo "ulimit -v unlimited" >> /etc/spack_container_rc.sh  && \
        echo "export CC=icx" >> /etc/spack_container_rc.sh  && \
        echo "export CXX=icpx" >> /etc/spack_container_rc.sh  && \
        echo "export FC=ifort" >> /etc/spack_container_rc.sh  && \
        echo "export jedi_cmake_ROOT=$(ls -d /opt/software/linux-*/jedi-cmake-*)" >> /etc/spack_container_rc.sh  && \
        echo "source /etc/spack_container_rc.sh" >> /etc/bash.bashrc && \
        printf "[credential]\n    helper = cache --timeout=7200\n" >> /root/.gitconfig && \
        # Replicate gitconfig for nonroot user.
        printf "[credential]\n    helper = cache --timeout=7200\n" >> /home/nonroot/.gitconfig && \
        chown -R nonroot:nonroot /home/nonroot/.gitconfig
        ENV BASH_ENV=/etc/spack_container_rc.sh

    # Labels for the image
    labels:
      app: ""
      mpi: "intel-oneapi-mpi"
