spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  definitions:
  - compilers: ['%aocc', '%apple-clang', '%gcc', '%intel', '%oneapi']
  - packages:
      - neptune-env ~debug +espc ^esmf@=8.9.0b11 snapshot=b11
      - neptune-env +debug +espc ^esmf@=8.9.0b11 snapshot=b11
      - neptune-python-env +xnrl ^neptune-env ~debug +espc ^esmf@=8.9.0b11 snapshot=b11

  specs:
    - matrix:
      - [$packages]
      - [$compilers]
      exclude:
      # Skip neptune-python-env with Intel Classic due to problems
      # with new versions of py-numpy, py-scipy, ...
      - neptune-python-env%intel
      # Same for LLVM compilers
      - neptune-python-env%clang
  packages:
    # Avoid duplicate builds of parallelio +pnetcdf and ~pnetcdf
    parallelio:
      require:
      - '~pnetcdf'
