spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  specs:
  - neptune-env ~debug +espc ^esmf@=8.9.0b12 snapshot=b12
  - neptune-env +debug +espc ^esmf@=8.9.0b12 snapshot=b12
  - neptune-python-env +xnrl ^neptune-env ~debug +espc ^esmf@=8.9.0b12 snapshot=b12
  packages:
    # Avoid duplicate builds of parallelio +pnetcdf and ~pnetcdf
    parallelio:
      require:
      - '~pnetcdf'
