modules:
  default:
    enable::
    - lmod
    lmod:
      include:
      # List of packages for which we need modules that are blacklisted by default# By default, do not create compiler modules
      # Compiler modules
      - apple-clang
      - gcc
      - intel-oneapi-compilers
      - llvm
      # MPI modules
      - cray-mpich
      - intel-mpi
      - intel-oneapi-mpi
      - mpich
      - mpt
      - openmpi
