# Template for NEPTUNE development
#
spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  specs:
  - neptune-env ~debug +openmp +espc +ncview ^esmf@=8.9.1
  - neptune-env +debug +openmp +espc +ncview ^esmf@=8.9.1
  - neptune-env ~debug ~openmp +espc +ncview ^esmf@=8.9.1
  - neptune-env +debug ~openmp +espc +ncview ^esmf@=8.9.1
  # Until we can build the entire set of dependencies for
  # neptune-python-env and jedi-neptune-env, we need to
  # add the required packages for the NEPTUNE standalone
  # model manually
  #- neptune-python-env    ^neptune-env ~debug +openmp +espc +ncview ^esmf@=8.9.1
  #- jedi-neptune-env +adp ^neptune-env ~debug +openmp +espc +ncview ^esmf@=8.9.1
  - py-numpy
  - crtm@3.1.3

  packages:
    # Turn on python variant for esmf
    esmf:
      require:
      - +python
