# Template for NEPTUNE development
#
spack:
  concretizer:
    unify: when_possible

  view: false
  include: []

  specs:
  - neptune-env ~debug +openmp +espc +ncview ^esmf@=8.9.1
  - neptune-env +debug +openmp +espc +ncview ^esmf@=8.9.1
  - neptune-env ~debug ~openmp +espc +ncview ^esmf@=8.9.1
  - neptune-env +debug ~openmp +espc +ncview ^esmf@=8.9.1
  # Until we can build the entire set of dependencies for
  # neptune-python-env and jedi-neptune-env, we need to
  # add the required packages for the NEPTUNE standalone
  # model manually
  #- neptune-python-env    ^neptune-env ~debug +openmp +espc +ncview ^esmf@=8.9.1
  #- jedi-neptune-env +adp ^neptune-env ~debug +openmp +espc +ncview ^esmf@=8.9.1
  - py-numpy
  # Let's assume/hope that by the time FALCON starts
  # testing with LLVM, we have moved from crtm v2 to v3
  - crtm@3.1.2
  #- crtm@v2.4.1-jedi.2

  packages:
    # Turn on python variant for esmf
    esmf:
      require:
      - +python
    # Avoid duplicate builds of parallelio +pnetcdf and ~pnetcdf
    parallelio:
      require:
      - ~pnetcdf
