# Template for CYLC (flow, rose, GUI). Supported with GCC only.
# Creates a view that allows users to define (manually for now)
# simple wrappers for cylc that can be aliased as "cylc":
#
##!/bin/bash
##CYLC_INSTALL_DIR=/path/to/env/view/bin
##PATH=${CYLC_INSTALL_DIR}:$PATH
##unset PYTHONPATH
##cylc "$@"
#
spack:
  concretizer:
    unify: true

  view:
    cylc:
      root: view
      select: [^python, bats]
      link: run
      link_type: symlink
  include: []

  specs:
  # These versions work with Python 3.11
  - py-cylc-flow@8.5.4
  - py-cylc-uiserver@1.7.1
  - bats
