# Template for CYLC (flow, rose, GUI). Supported with GCC only
spack:
  concretizer:
    unify: true

  view: false
  include: []

  definitions:
  - compilers: ['%gcc']
  - packages:
      - py-cylc-flow@8.3.6
      - py-cylc-rose@1.3.0
      - py-cylc-uiserver@1.3.0

  specs:
    - matrix:
      - [$packages]
      - [$compilers]
