packages:
  gmake:
    buildable: false
    externals:
    - spec: gmake@4.3
      prefix: /usr
  gcc-runtime:
    buildable: false
    externals:
    - spec: gcc-runtime@13.3.0
      prefix: /usr
  grep:
    externals:
    - spec: grep@3.11
      prefix: /usr
  wget:
    externals:
    - spec: wget@1.21.4
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.38.2~cpanm+opcode+open+shared+threads
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.9.0
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@9.4
      prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.8.1
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.7
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.2.1
      prefix: /usr
  git:
    externals:
    - spec: git@2.43.0~tcltk
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.9
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.10
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.23.0
      prefix: /usr
