packages:
  # Package constraints.
  awscli-v2:
    require:
    - "@2.22.4"
  ewok-env:
    require:
    - +ecflow
  py-awscrt:
    require:
    - "@0.19.19"
  py-botocore:
    require:
    - "@1.34.162"
  py-boto3:
    require:
    - "@1.34.162"
  py-netcdf4:
    require:
    - "@1.7.2"

  # System packages.
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.42+gold~headers
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@9.4
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.10
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.9.0
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.2.1
      prefix: /usr
  git:
    externals:
    - spec: git@2.43.0~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@3.4.1
      prefix: /usr
  gmake:
    buildable: false
    externals:
    - spec: gmake@4.3
      prefix: /usr
  grep:
    externals:
    - spec: grep@3.11
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.23.0
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.7
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.38.2~cpanm+opcode+open+shared+threads
      prefix: /usr
  pkgconf:
    externals:
    - spec: pkgconf@1.8.1
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.9
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.35
